version: '3.8'

services:
  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      retries: 10
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  nimestreamapi-backend:
    image: saepulid07/nimestreamapi-backend:latest
    container_name: nimestreamapi-backend
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: always
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health-check"]
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nimestreamapi-backend
    networks:
      - app-net

volumes:
  dbdata:

networks:
  app-net:
    driver: bridge
