version: '3.8'

services:
  vpn-client:
    image: dperson/openvpn-client
    container_name: vpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /root/private_files/vpngate_118.136.140.187_udp_1206.ovpn:/vpn/vpn.conf
    environment:
      - TZ=Asia/Jakarta
    command: ''
    restart: always
    networks:
      - vpn-net

  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      retries: 10
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - vpn-net

  nimestreamapi-backend:
    image: saepulid07/nimestreamapi-backend:latest
    container_name: nimestreamapi-backend
    env_file:
      - .env
    network_mode: "service:vpn-client"
    depends_on:
      postgresdb:
        condition: service_healthy
      vpn-client:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health-check"]
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    network_mode: "service:vpn-client" 
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vpn-client

volumes:
  dbdata:

networks:
  vpn-net:
    driver: bridge
