services:
  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      retries: 10
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}  
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgresdb
    networks:
      - app-net

  nimestreamapi-backend:
    image: saepulid07/nimestreamapi-backend:latest
    container_name: nimestreamapi-backend
    env_file:
      - .env
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: always
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health-check"]
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 30s

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/uploads:/var/www/uploads
    depends_on:
      - nimestreamapi-backend
      - minio
      - pgadmin
    networks:
      - app-net

volumes:
  dbdata:
  minio_data:

networks:
  app-net:
    driver: bridge
