package seed

import (
	"time"

	"github.com/lib/pq"
	"github.com/muhammadsaefulr/NimeStreamAPI/internal/domain/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedDrakor(db *gorm.DB) error {
	drakorSeed := []model.MovieDetails{
		{
			MovieID:      "strong-woman-do-bong-soon",
			MovieType:    "kdrama",
			ThumbnailURL: "https://image.tmdb.org/t/p/original/your_poster_path.jpg",
			Title:        "Strong Woman Do Bong Soon",
			Rating:       "8.7",
			Producer:     "JTBC",
			Status:       "Finished Airing",
			Studio:       "Drama House, JS Pictures",
			ReleaseDate:  "2017-02-24",
			Synopsis:     "Do Bong‑soon was born with superhuman strength. Recruited as bodyguard to a gaming‑chaebol heir, she uses her power to fight crime while juggling a love triangle with her childhood friend and her boss.",
			Genres:       pq.StringArray{"Fantasy", "Action", "Romance", "Comedy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "business-proposal",
			MovieType:    "kdrama",
			ThumbnailURL: "https://hubpages.com/assets/resized/business-proposal-review.jpg",
			Title:        "Business Proposal",
			Rating:       "8.1",
			Producer:     "SBS TV",
			Status:       "Finished Airing",
			Studio:       "StudioS, Kakao Entertainment, Kross Pictures",
			ReleaseDate:  "2022-02-28",
			Synopsis:     "A romantic comedy where Shin Ha‑ri goes on a blind date disguised as her friend and ends up dating her CEO, Kang Tae‑moo.",
			Genres:       pq.StringArray{"Romantic Comedy", "Workplace", "Comedy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "the-trauma-code-heroes-on-call",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/735qBe_4c.jpg?v=1",
			Title:        "The Trauma Code: Heroes on Call",
			Rating:       "9.1",
			Producer:     "Lee Do Yoon",
			Status:       "Unknown",
			Studio:       "Netflix",
			ReleaseDate:  "2025-01-24",
			Synopsis:     "Baek Gang Hyeok, a genius trauma surgeon with experience in conflict zones...",
			Genres:       pq.StringArray{"Action", "Comedy", "Drama", "Medical"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "alchemy-of-souls",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/Beg4z_4c.jpg?v=1",
			Title:        "Alchemy of Souls",
			Rating:       "9.1",
			Producer:     "Park Joon Hwa",
			Status:       "Completed",
			Studio:       "tvN",
			ReleaseDate:  "2022-06-18",
			Synopsis:     "In the fictional country of Daeho, young mages struggle to overcome twisted fates...",
			Genres:       pq.StringArray{"Action", "Historical", "Romance", "Fantasy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "moving",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/x4kN8X_4c.jpg?v=1",
			Title:        "Moving",
			Rating:       "9.0",
			Producer:     "Park In Je",
			Status:       "Completed",
			Studio:       "Disney+",
			ReleaseDate:  "2023-08-09",
			Synopsis:     "Kim Bong Seok, Jang Hui Su, and Lee Gang Hun, seemingly typical high school students...",
			Genres:       pq.StringArray{"Action", "Thriller", "Mystery", "Supernatural"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "twinkling-watermelon",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/2w44jE_4c.jpg?v=1",
			Title:        "Twinkling Watermelon",
			Rating:       "9.2",
			Producer:     "Son Jung Hyun",
			Status:       "Completed",
			Studio:       "tvN",
			ReleaseDate:  "2023-09-25",
			Synopsis:     "In 2023, high school student Eun Gyeol, a CODA with a passion for music...",
			Genres:       pq.StringArray{"Romance", "Youth", "Drama", "Fantasy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "when-life-gives-you-tangerines",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/5v8b2y_4c.jpg?v=1",
			Title:        "When Life Gives You Tangerines",
			Rating:       "9.4",
			Producer:     "Kim Won Suk",
			Status:       "Completed",
			Studio:       "Netflix",
			ReleaseDate:  "2025-03-07",
			Synopsis:     "It is a story that resembles a tribute to our parents' tender and still youthful seasons...",
			Genres:       pq.StringArray{"Romance", "Life", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "weak-hero-class-1",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/pq2lr_4c.jpg?v=1",
			Title:        "Weak Hero Class 1",
			Rating:       "9.1",
			Producer:     "Park Dhan Hee",
			Status:       "Unknown",
			Studio:       "Wavve",
			ReleaseDate:  "2022-11-18",
			Synopsis:     "Yeon Shi Eun is a model student who ranks at the top of his high school...",
			Genres:       pq.StringArray{"Action", "Youth", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "reply-1988",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/EVe0p_4c.jpg?v=1",
			Title:        "Reply 1988",
			Rating:       "9.0",
			Producer:     "Shin Won Ho, Yoo Hak Chan",
			Status:       "Completed",
			Studio:       "tvN",
			ReleaseDate:  "2015-11-06",
			Synopsis:     "Five childhood friends, who all live in the same neighborhood of Seoul...",
			Genres:       pq.StringArray{"Comedy", "Romance", "Life", "Youth"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "flower-of-evil",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/WAEAp_4c.jpg?v=1",
			Title:        "Flower of Evil",
			Rating:       "9.1",
			Producer:     "Kim Chul Gyu, Yoon Jong Ho",
			Status:       "Completed",
			Studio:       "tvN",
			ReleaseDate:  "2020-07-29",
			Synopsis:     "Although Baek Hui Seong is hiding a dark secret surrounding his true identity...",
			Genres:       pq.StringArray{"Thriller", "Romance", "Crime", "Melodrama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "hospital-playlist-season-2",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/dKY0d_4c.jpg?v=1",
			Title:        "Hospital Playlist Season 2",
			Rating:       "9.1",
			Producer:     "Shin Won Ho",
			Status:       "Completed",
			Studio:       "tvN",
			ReleaseDate:  "2021-06-17",
			Synopsis:     "Everyday is extraordinary for five doctors and their patients inside a hospital...",
			Genres:       pq.StringArray{"Romance", "Life", "Drama", "Medical"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "move-to-heaven",
			MovieType:    "kdrama",
			ThumbnailURL: "https://i.mydramalist.com/Rle36_4c.jpg?v=1",
			Title:        "Move to Heaven",
			Rating:       "9.1",
			Producer:     "Kim Sung Ho",
			Status:       "Unknown",
			Studio:       "Netflix",
			ReleaseDate:  "2021-05-14",
			Synopsis:     "Han Geu Roo is an autistic 20-year-old who works for his father’s trauma cleanup company...",
			Genres:       pq.StringArray{"Life", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "descendants-of-the-sun",
			MovieType:    "kdrama",
			ThumbnailURL: "https://redbubble.com/path-to-poster.jpg",
			Title:        "Descendants of the Sun",
			Rating:       "8.2",
			Producer:     "KBS2",
			Status:       "Finished Airing",
			Studio:       "KBS Drama Production, Next Entertainment World, Barunson Inc.",
			ReleaseDate:  "2016-02-24",
			Synopsis:     "A soldier Yoo Si‑jin and a surgeon Kang Mo‑yeon fall in love while facing dangers in a war‑like setting.",
			Genres:       pq.StringArray{"Romance", "Melodrama", "Action"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
	}

	for _, drakor := range drakorSeed {
		if err := db.Clauses(clause.OnConflict{DoNothing: true}).Create(&drakor).Error; err != nil {
			return err
		}
	}

	return nil
}
