package seed

import (
	"time"

	"github.com/lib/pq"
	"github.com/muhammadsaefulr/NimeStreamAPI/internal/domain/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SeedMovie(db *gorm.DB) error {
	movieSeed := []model.MovieDetails{
		{
			MovieID:      "the-fantastic-four-first-steps",
			MovieType:    "movie",
			Title:        "The Fantastic Four: First Steps",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
			Rating:       "7.3",
			Producer:     "",
			Status:       "Released",
			Studio:       "Marvel Studios",
			ReleaseDate:  "2025-07-23",
			Synopsis:     "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
			Genres:       pq.StringArray{"Science Fiction", "Adventure"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "a-normal-woman",
			MovieType:    "movie",
			Title:        "A Normal Woman",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/p8QqvttODrPYdJLjAUvcUsJtDTD.jpg",
			Rating:       "7.0",
			Producer:     "",
			Status:       "Released",
			Studio:       "Soda Machine Films",
			ReleaseDate:  "2025-07-23",
			Synopsis:     "When an unidentified disease starts to upend her life, a socialite must unravel the mystery behind it — before her whole sense of self falls apart.",
			Genres:       pq.StringArray{"Drama", "Thriller", "Horror"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "lilo-and-stitch",
			MovieType:    "movie",
			Title:        "Lilo & Stitch",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/c32TsWLES7kL1uy6fF03V67AIYX.jpg",
			Rating:       "7.3",
			Producer:     "",
			Status:       "Released",
			Studio:       "Walt Disney Pictures",
			ReleaseDate:  "2025-05-17",
			Synopsis:     "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
			Genres:       pq.StringArray{"Family", "Science Fiction", "Comedy", "Adventure"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "happy-gilmore-2",
			MovieType:    "movie",
			Title:        "Happy Gilmore 2",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
			Rating:       "8.3",
			Producer:     "",
			Status:       "Released",
			Studio:       "Happy Madison Productions",
			ReleaseDate:  "2025-07-25",
			Synopsis:     "Happy Gilmore isn’t done with golf — not by a long shot. Adam Sandler’s short-fused legend swings for a comeback to make his kid’s dream come true.",
			Genres:       pq.StringArray{"Comedy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "how-to-train-your-dragon",
			MovieType:    "movie",
			Title:        "How to Train Your Dragon",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg",
			Rating:       "8.1",
			Producer:     "",
			Status:       "Released",
			Studio:       "DreamWorks Animation",
			ReleaseDate:  "2025-06-06",
			Synopsis:     "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon...",
			Genres:       pq.StringArray{"Fantasy", "Family", "Action"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "superman",
			MovieType:    "movie",
			Title:        "Superman",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
			Rating:       "7.4",
			Producer:     "",
			Status:       "Released",
			Studio:       "DC Studios",
			ReleaseDate:  "2025-07-09",
			Synopsis:     "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
			Genres:       pq.StringArray{"Science Fiction", "Adventure", "Action"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "materialists",
			MovieType:    "movie",
			Title:        "Materialists",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
			Rating:       "6.8",
			Producer:     "",
			Status:       "Released",
			Studio:       "A24",
			ReleaseDate:  "2025-06-12",
			Synopsis:     "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
			Genres:       pq.StringArray{"Romance", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "demon-slayer-kimetsu-no-yaiba-infinity-castle",
			MovieType:    "movie",
			Title:        "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
			Rating:       "6.5",
			Producer:     "",
			Status:       "Released",
			Studio:       "ufotable",
			ReleaseDate:  "2025-07-18",
			Synopsis:     "Tanjiro and the Hashira are plunged into a mysterious space by Muzan Kibutsuji. The battleground is set for the final battle between the Demon Slayer Corps and the demons in the Infinity Castle.",
			Genres:       pq.StringArray{"Animation", "Action", "Fantasy", "Thriller"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "xxx",
			MovieType:    "movie",
			Title:        "xXx",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
			Rating:       "6.0",
			Producer:     "",
			Status:       "Released",
			Studio:       "Columbia Pictures",
			ReleaseDate:  "2002-08-09",
			Synopsis:     "Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government recruits him to gather information about a world-threatening organization, things get explosive.",
			Genres:       pq.StringArray{"Action", "Adventure", "Thriller", "Crime"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "dangerous-animals",
			MovieType:    "movie",
			Title:        "Dangerous Animals",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/9tk3Si960hg4E49eMt81dS7Qe9Z.jpg",
			Rating:       "6.8",
			Producer:     "",
			Status:       "Released",
			Studio:       "LD Entertainment",
			ReleaseDate:  "2025-06-05",
			Synopsis:     "A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must escape before he carries out a ritualistic feeding to the sharks.",
			Genres:       pq.StringArray{"Horror", "Thriller"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "m3gan-2",
			MovieType:    "movie",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
			Title:        "M3GAN 2.0",
			Rating:       "7.7",
			Producer:     "",
			Status:       "Released",
			Studio:       "Universal Pictures",
			ReleaseDate:  "2025-06-25",
			Synopsis:     "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
			Genres:       pq.StringArray{"Action", "Science Fiction", "Thriller"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "man-with-no-past",
			MovieType:    "movie",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/eWHvROuznSzcxBAAkzX1X0Rmzoe.jpg",
			Title:        "Man with No Past",
			Rating:       "6.8",
			Producer:     "",
			Status:       "Released",
			Studio:       "Unknown",
			ReleaseDate:  "2025-01-13",
			Synopsis:     "Waking up in an unfamiliar city, a man with no memory must confront the mysteries of his own identity. However, his desperate search to uncover the past pits him against a powerful enemy, leading to a showdown that ultimately reveals the truth.",
			Genres:       pq.StringArray{"Action", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "karate-kid-legends",
			MovieType:    "movie",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/AEgggzRr1vZCLY86MAp93li43z.jpg",
			Title:        "Karate Kid: Legends",
			Rating:       "7.2",
			Producer:     "",
			Status:       "Released",
			Studio:       "Unknown",
			ReleaseDate:  "2025-05-08",
			Synopsis:     "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough.",
			Genres:       pq.StringArray{"Action", "Adventure", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "bride-hard",
			MovieType:    "movie",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
			Title:        "Bride Hard",
			Rating:       "5.8",
			Producer:     "",
			Status:       "Released",
			Studio:       "Unknown",
			ReleaseDate:  "2025-06-19",
			Synopsis:     "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When mercenaries crash the party, Sam must fight without blowing her cover.",
			Genres:       pq.StringArray{"Action", "Comedy"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
		{
			MovieID:      "ice-road-vengeance",
			MovieType:    "movie",
			ThumbnailURL: "https://image.tmdb.org/t/p/w500/cQN9rZj06rXMVkk76UF1DfBAico.jpg",
			Title:        "Ice Road: Vengeance",
			Rating:       "7.0",
			Producer:     "",
			Status:       "Released",
			Studio:       "Unknown",
			ReleaseDate:  "2025-06-27",
			Synopsis:     "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus, McCann and his guide encounter mercenaries and must fight to survive.",
			Genres:       pq.StringArray{"Action", "Thriller", "Drama"},
			CreatedAt:    time.Now(),
			UpdatedAt:    time.Now(),
		},
	}

	for _, movie := range movieSeed {
		if err := db.Clauses(clause.OnConflict{DoNothing: true}).Create(&movie).Error; err != nil {
			return err
		}
	}

	return nil
}
